#!/bin/bash
NAME="zlib"
VERSION="1.3.1"
TARBALL_URL="https://github.com/madler/zlib/releases/download/v$VERSION/$NAME-$VERSION.tar.xz"

build() {
  cd "$SRCDIR"
  CFLAGS+=" -ffat-lto-objects"
  ./configure --prefix=/usr

  make -j"$JOBS"
}

package() {
  cd "$SRCDIR"
  make DESTDIR="$INSTALLDIR" install
}

configure() {
  :
}
