#!/bin/bash
NAME="kmod"
VERSION="34.2"
TARBALL_URL="https://www.kernel.org/pub/linux/utils/kernel/kmod/kmod-$VERSION.tar.xz"

build() {
  cd "$SRCDIR"
  meson setup build \
    --prefix=/usr \
    --libdir=/usr/lib \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dopenssl=enabled

  meson compile -C build -j"$JOBS"
}

package() {
  cd "$SRCDIR"
  meson install -C build --destdir="$INSTALLDIR"
}

configure() {
  mkdir -p "$INSTALLDIR/etc/{depmod.d,modprobe.d}"
}
