#!/bin/bash
NAME="kbd"
VERSION="2.8.0"
TARBALL_URL="https://www.kernel.org/pub/linux/utils/kbd/kbd-$VERSION.tar.xz"

build() {
  cd "$SRCDIR"
  ./configure --prefix=/usr --libdir=/usr/lib
  make -j"$JOBS"
}

package() {
  cd "$SRCDIR"
  make install DESTDIR="$INSTALLDIR"
}

configure() {
  :
}
