#!/bin/bash
NAME="pam"
VERSION="1.7.0"
TARBALL_URL="https://github.com/linux-pam/linux-pam/releases/download/v$VERSION/Linux-PAM-$VERSION.tar.xz"

build() {
  cd "$SRCDIR"
  meson setup build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --buildtype=release \
    --libdir=/usr/lib \
    -Ddocs=disabled

  meson compile -C build -j"$JOBS"
}

package() {
  cd "$SRCDIR"
  meson install -C build --destdir "$INSTALLDIR"
}

configure() {
  cd "$INSTALLDIR"

  mkdir -p etc etc/pam.d

  for service in login su sudo agetty other; do
    install -Dm644 $PKGDIR/pam-service etc/pam.d/$service
  done

  install -Dm644 $PKGDIR/nsswitch.conf etc/nsswitch.conf
}
