#!/bin/bash
NAME="libaudit"
VERSION="4.0.5"
TARBALL_URL="https://github.com/linux-audit/audit-userspace/archive/refs/tags/v$VERSION.tar.gz"

build() {
  cd "$SRCDIR"
  autoreconf -f --install
  ./configure --prefix=/usr \
    --sysconfdir=/etc \
    --libdir=/usr/lib

  make -j"$JOBS"
}

package() {
  cd "$SRCDIR"
  make install DESTDIR="$INSTALLDIR"
}

configure() {
  :
}
