#!/bin/bash
NAME="util-linux"
VERSION="2.41"
TARBALL_URL="https://github.com/util-linux/util-linux/archive/refs/tags/v$VERSION.tar.gz"

build() {
  cd "$SRCDIR"
  ./autogen.sh
  ./configure --prefix=/usr \
    --sysconfdir=/etc \
    --libdir=/usr/lib \
    --disable-nls \
    --without-systemd \
    --without-python

  make -j"$JOBS"
}

package() {
  cd "$SRCDIR"
  make install-strip DESTDIR="$INSTALLDIR"
}

configure() {
  cd "$INSTALLDIR"
  mkdir -p etc
  ln -s /proc/self/mounts etc/mtab
}
