#!/bin/bash
NAME="openrc"
VERSION="0.62.2"
TARBALL_URL="https://github.com/OpenRC/openrc/archive/refs/tags/$VERSION.tar.gz"

build() {
  cd "$SRCDIR"
  meson setup build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dos=Linux

  meson compile -C build -j"$JOBS"
}

package() {
  cd "$SRCDIR"
  meson install -C build --destdir "$INSTALLDIR"
}

configure() {
  cd "$INSTALLDIR"

  ln -s /usr/bin/openrc-init sbin/init

  mkdir -p etc etc/init.d var/cache/rc run/openrc etc/runlevels/{boot,sysinit,default,shutdown} proc
  
  install -Dm644 $PKGDIR/fstab etc/fstab

  echo "localhost" > etc/hostname

  cd etc/init.d
  for n in {1..12}; do
    ln -sf agetty agetty.tty$n
  done
  cd "$INSTALLDIR"

  cd etc/runlevels
  for n in {1..12}; do
    ln -s /etc/init.d/agetty.tty$n default/ || true
  done
  ln -s /etc/init.d/udev sysinit/ || true
  ln -s /etc/init.d/udev-trigger sysinit/ || true
  ln -s /etc/init.d/devfs sysinit/ || true
  ln -s /etc/init.d/dmesg sysinit/ || true
  ln -s /etc/init.d/loopback boot/ || true
  ln -s /etc/init.d/hostname boot/ || true
  ln -s /etc/init.d/sysfs boot/ || true
  ln -s /etc/init.d/modules boot/ || true
  ln -s /etc/init.d/hwclock boot/ || true
  unlink default/netmount || true
}
