#!/bin/bash
NAME="busybox"
VERSION="1.36.1"
TARBALL_URL="https://github.com/mirror/busybox/archive/refs/tags/$(echo "$VERSION" | sed 's/\./_/g').tar.gz"

build() {
  make defconfig

  sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/' .config
  sed -i 's/CONFIG_TC=y/CONFIG_TC=n/' .config
  sed -i 's/# CONFIG_BASH_IS_ASH is not set/CONFIG_BASH_IS_ASH=y/' .config
  sed -i 's/CONFIG_BASH_IS_NONE=y/CONFIG_BASH_IS_NONE=n/' .config
  sed -i 's/CONFIG_INIT=y/CONFIG_INIT=n/' .config
  sed -i 's/CONFIG_LINUXRC=y/CONFIG_LINUXRC=n/' .config
  sed -i 's/CONFIG_BB_SYSCTL=y/CONFIG_BB_SYSCTL=n/' .config

  make -j"$JOBS"
}

install() {
  make CONFIG_PREFIX="$INSTALLDIR" install
}

configure() {
  :
}
