#!/bin/bash
NAME="libtirpc"
VERSION="1.3.6"
TARBALL_URL="https://downloads.sourceforge.net/sourceforge/libtirpc/${NAME}-${VERSION}.tar.bz2"

build() {
  patch -Np1 -i ../gcc15.patch || true
  ./configure --prefix=/usr --libdir=/usr/lib --disable-gssapi --disable-static
  make -j"$JOBS"
}

install() {
  make DESTDIR="$INSTALLDIR" install
}

configure() {
  :
}
